; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Windows POC"
#define MyAppVersion "1.0"
#define MyAppPublisher "WindowsPOC Inc"
#define MyAppURL "http://www.example.com/"
#define MyAppExeName "settings.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{6F2370F7-5949-4CEF-8C71-3BC392D685C6}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\WindowsPOC
DisableProgramGroupPage=yes
OutputBaseFilename=poc_setup
Compression=lzma
SolidCompression=yes
PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\settings.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\poc_service.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "dist\prepenv.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\prepenv.exe"; Parameters: "setup"; Flags: runasoriginaluser;
Filename: "{app}\poc_service.exe"; Parameters: "install";
Filename: "{app}\poc_service.exe"; Parameters: "start";
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: postinstall skipifsilent

[UninstallRun]
Filename: "{app}\poc_service.exe"; Parameters: "stop";
Filename: "{app}\poc_service.exe"; Parameters: "remove";
Filename: "{app}\prepenv.exe"; Parameters: "teardown";
